site_name: ServerManagement Documentation
repo_url: https://github.com/twillin912/PSServerManagement
theme: readthedocs
pages:
  - Home: index.md
  - ServerManagementTools Basics:
    - Quick Start: quickstart.md
  - Functions:
    - Get-DfsrBacklogStatus: Functions/Get-DfsrBacklogStatus.md
    - Get-IISLogPath: Functions/Get-IISLogPath.md
    - Get-RDSession: Functions/Get-RDSession.md
    - Invoke-LogRotation: Functions/Invoke-LogRotation.md
